# Generated by Django 5.2.4 on 2025-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Numéro de téléphone gambien (7 chiffres, unique)', max_length=7, unique=True),
        ),
    ]
