# Generated by Django 5.2.4 on 2025-08-08 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aprovision', '0001_initial'),
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='product.product'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='reference_commande',
            field=models.ForeignKey(blank=True, help_text='Commande associée (pour les ventes)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='reference_depense',
            field=models.ForeignKey(blank=True, help_text='Dépense associée (pour les approvisionnements)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aprovision.depense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='type_depense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='aprovision.typedepense'),
        ),
    ]
