# Generated by Django 5.2.4 on 2025-08-04 13:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant de ce paiement', max_digits=20)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('mobile', 'Mobile Money'), ('bank', 'Virement Bancaire'), ('credit', 'Crédit'), ('other', 'Autre')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes sur ce paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
