# Generated by Django 5.2.4 on 2025-08-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('order', '0008_alter_payment_options_remove_payment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client associé (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='client.client'),
        ),
    ]
